kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-mlflow-pv-claim
  namespace: mlops-puj
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: aws-efs
  volumeName: data-mlflow-pv-storage
  resources:
    requests:
      storage: 1Gi