apiVersion: v1
kind: PersistentVolume
metadata:
  name: metadata-mlflow-pv-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mlops/metadata
    server: fs-036586b5c4567a771.efs.us-east-1.amazonaws.com
  storageClassName: aws-efs
  volumeMode: Filesystem    