apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: mlops-puj
  labels:
    app: minio
    env: mlops-puj
spec:
  ports:
    - port: 9000
      targetPort: 9000
      name: port1minio
    - port: 9001
      targetPort: 9001
      name: port2minio
  selector:
    app: minio
    env: mlops-puj
