apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: mlops-puj
  labels:
    app: minio
    env: mlops-puj
spec:
  type: LoadBalancer
  ports:
    - port: 9090
  selector:
    app: minio
    env: mlops-puj
