apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  namespace: mlops-puj
  labels:
    app: minio
    env: mlops-puj
spec:
  selector:
    matchLabels:
      app: minio
      env: mlops-puj
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: minio
        env: mlops-puj
    spec:
      containers:
      - name: minio-container
        image: quay.io/minio/minio:latest
        ports:
        - containerPort: 9090
        command:
        - /bin/bash
        - -c
        args: 
        - minio server /data --console-address :9090
        env:
        - name: MINIO_ROOT_USER
          value: "admin"
        - name: MINIO_ROOT_PASSWORD
          value: "supersecret"
        volumeMounts:
        - mountPath: "/data"
          name: mlops-mlflow-pv-storage
      volumes:
        - name: mlops-mlflow-pv-storage
          persistentVolumeClaim:
            claimName: mlops-mlflow-pv-claim