apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-deployment
  namespace: mlops-puj
  labels:
    app: mlflow
    env: mlops-puj
spec:
  selector:
    matchLabels:
      app: mlflow
      env: mlops-puj
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mlflow
        env: mlops-puj
    spec:
      containers:
      - name: mlflow-container
        image: mlops-puj/mlflow:1.0.0
        ports:
        - containerPort: 5000
        env:
        - name: DB_USERNAME
          value: "topicosIA"
        - name: DB_PASSWORD
          value: "topicosIA"
        - name: DB_URL
          value: "metadata-db-mlfow-svc:5432"
        - name: DB_NAME
          value: "metadata-mlfow"    
        - name: ARTIFACT_STORE
          value: "s3://mlflows3/artifacts"            
        volumeMounts:
        - mountPath: "/data"
          name: metadata-mlflow-pv-storage
      volumes:
        - name: metadata-mlflow-pv-storage
          persistentVolumeClaim:
            claimName: metadata-mlflow-pv-claim