kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mlops-mlflow-pv-claim
  namespace: mlops-puj
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: my-local-storage
  resources:
    requests:
      storage: 1Gi