apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-x-deployment
  namespace: mlops-puj
  labels:
    app: database-x
    env: mlops-puj
spec:
  selector:
    matchLabels:
      app: database-x
      env: mlops-puj
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: database-x
        env: mlops-puj
    spec:
      containers:
      - name: db-x
        image: mysql:8.0
        env:
        - name: MYSQL_DATABASE
          value: "training"
        - name: MYSQL_ROOT_PASSWORD
          value: "topicosIA"
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: mlops-f-pv-storage
      volumes:
        - name: mlops-f-pv-storage
          persistentVolumeClaim:
            claimName: mlops-f-pv-claim
