apiVersion: v1
kind: PersistentVolume
metadata:
  name: mlops-m-pv-storage
  labels:
    type: local
spec:
  storageClassName: my-local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/estudiante/TopicosAIA/Talleres/k8s/volumes/m"
