apiVersion: v1
kind: PersistentVolume
metadata:
  name: mlops-f-pv-storage
  labels:
    type: local
spec:
  storageClassName: my-local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/c/Users/DEIMER\ BALLESTEROS/Downloads/volumes/f"
