apiVersion: v1
kind: Service
metadata:
  name: mlops-puj-process-data-service
  namespace: mlops-puj
spec:
  type: NodePort
  ports:
  - name: process-data-mlops
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: process-data-app
    env: mlops-puj
