apiVersion: v1
kind: Service
metadata:
  name: mlops-puj-z-db-service
  namespace: mlops-puj
spec:
  type: NodePort
  ports:
  - name: db-z-mlops
    port: 8080
    targetPort: 8080
    nodePort: 30002
    protocol: TCP
  selector:
    app: database-z
    env: mlops-puj
