apiVersion: v1
kind: Service
metadata:
  name: mlops-puj-x-db-service
  namespace: mlops-puj
spec:
  type: NodePort
  ports:
  - name: db-x-mlops
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: database-x
    env: mlops-puj
