apiVersion: v1
kind: Service
metadata:
  name: mlops-puj-save-data
  namespace: mlops-puj
spec:
  type: NodePort
  ports:
  - name: save-data-mlops
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: save-data-app
    env: mlops-puj
